### ISSUE TITLE
Map position & zoom

### ISSUE THREAD

**Issue by dillix** [victorzimmer/MapKit#10]
Hi,

First i would like to say thanks for this great plugin!

Is there any option to setup map position and zoom level like in google maps?

**Comment by victorzimmer** [comment]
First off, you're more than welcome! Thank you for using it :)

This is a planned feature (and mostly finished one too) for the next version, I just have had very limited time recently. I'll see if I can't whip together a quick mini version with only these features for release in one of the coming days.

Might also include the code I have for multiplatform support, if not that'll be in the next version.

**Comment by dillix** [comment]
I found objective c code for this support here: https://github.com/johndpope/MKMapViewZoom/blob/master/MKMapView%2BZoomLevel.m

Also I can donate for speedup development of this feature.

**Comment by victorzimmer** [comment]
I do this for free because I think something like MapKit should be available to anyone using Cordova. Any donation would be greatly appreciated and would of course be a step towards making this more of a part-time job then a hobby. However, currently I have a full-time job along with this and I would appreciate if you hold off on feature-specific donations until the feature is released. I will however try to get these features done today if I’m able!

Victor

**Comment by victorzimmer** [comment]
Hey @dillix I just wanted to inform you that the features you requested was added with the latest pull and should now be available if you install the newest version from GitHub.

I don't have the time to update the docs, but here's a quick rundown:

map.getMapCenter(callback)
Callback will get an array where [0] is lat and [1] is lon

map.setMapCenter({centerLat: 58, centerLon: 11, animated: true})
Simple as that

map.setMapRegion({centerLat: 58, centerLon: 11, spanLat: 2, spanLon: 2 animated: true})
Zoom can be set by telling MapKit what area you want to make sure is visible.

I'm terribly sorry it took me so long to get it done, I've just had a lot to do.
I'll go ahead and close this issue now, please reopen it if there's anything wrong!

Victor
